extern float WATER_HEIGHT;
extern int chunk_render_distance;
extern const int xMapChunks;
extern const int yMapChunks;
extern int chunkWidth;
extern int chunkHeight;
extern int gridPosX;
extern int gridPosY;
extern float originX;
extern float originY;
extern bool GRASS_ENABLED;